          script: |
            cd /var/www/vendapp
            git pull origin main
            npm install
            npm run build
            pm2 restart vendapp || pm2 start serve --name "vendapp" -- -s dist -l 3000
